name: Build and Upload Image to DockerHub

on:
  push:
    branches:
      [main, develop]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        platforms: linux/amd64
        push: true
        tags: |
          index.docker.io/${{ secrets.DOCKERHUB_USERNAME}}/aivle_testproject_back:latest
          index.docker.io/${{ secrets.DOCKERHUB_USERNAME}}/aivle_testproject_back:${{ github.sha }}
        file: ./Dockerfile
